[tool.poetry]
authors = ["Will Frey <jfrey89@gmail.com>"]
description = ""
license = "MIT"
name = "biteme"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.9"

black = "^20.8b1"
click = "^7.1.2"
isort = "^5.5.4"
more-itertools = "^8.5.0"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = {git = "https://github.com/psf/black.git"}
darglint = "^1.5.4"
flake8 = "^3.8.3"
flake8-adjustable-complexity = "^0.0.1"
flake8-annotations = "^2.4.1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.1.4"
flake8-class-attributes-order = "^0.1.1"
flake8-cognitive-complexity = "^0.1.0"
flake8-comprehensions = "^3.2.3"
flake8-docstrings = "^1.5.0"
flake8-eradicate = "^0.4.0"
flake8-expression-complexity = "^0.0.8"
flake8-printf-formatting = "^1.1.0"
flake8-pyi = "^20.5.0"
flake8-pytest-style = "^1.3.0"
flake8-quotes = "^3.2.0"
flake8-rst-docstrings = "^0.0.14"
flake8-tidy-imports = "^4.1.0"
flake8-typing-imports = "^1.9.0"
flakehell = "^0.6.1"
ipykernel = "^5.3.4"
isort = "^5.6.1"
mypy = "^0.790"
pep8-naming = "^0.11.1"
pytest = "^6.1.0"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
pytest-randomly = "^3.4.1"
wemake-python-styleguide = {git = "https://github.com/wemake-services/wemake-python-styleguide.git"}

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0a5"]

[tool.black]
target-version = ["py39"]

[tool.isort]
combine_as_imports = true
combine_star = true
profile = "black"
remove_redundant_aliases = true
